services:
  limesurvey:
    image: limesurvey:6.14.3
    volumes:
      - ./plugins:/var/www/html/upload/plugins
      - ./limesurvey-cron:/etc/cron.d/limesurvey-cron
      - ./logs:/var/log/app
      - lime:/var/www/html
    networks:
      - lime_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - lime_pgsql
    env_file:
      - ./.env

  web:
    image: docker.io/nginx:alpine
    networks:
      - lime_network
    depends_on:
      - limesurvey
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - lime:/var/www/html

  lime_pgsql:
    container_name: pgsql-limesurvey
    image: postgres:14.10
    environment:
        POSTGRES_DB: ${LS_DB_NAME:-limesurvey}
        POSTGRES_USER: ${LS_DB_USER:-admin}
        POSTGRES_PASSWORD: ${LS_DB_PASSWORD:-password}
    volumes:
        - lime_database:/var/lib/postgresql/data
    networks:
        - lime_network
    ports:
        - 6542:5432
    
volumes:
  lime:
    name: lime_data_dev
  lime_database:
    name: lime_database_dev
networks:
  lime_network:
    name: lime_network_dev